<!DOCTYPE html>
<html lang="en">
 <head>
  <meta http-equiv="Content-Type" content="text/html; charset=<?= $this->charset ?>"/>
  <meta name="msapplication-TileColor" content="#ffffff"/>
  <meta name="msapplication-TileImage" content="/mstile-144x144.png"/>
  <meta name="author" content="Vivien Richter"/>
  <meta name="description" content="The Second Life Shinto Shrine Register (SLSR) is a association of Shinto shrines in Second Life."/>
  <meta name="keywords" content="Second Life, SL, Shinto, shrine register, board"/>
  <title><?= $this->model->getPageTitle() ?></title>
  <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico"/>
  <link rel="icon" type="image/png" href="/favicon.png" sizes="32x32"/>
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/>
  <link rel="stylesheet" href="/css/markers.css" media="all"/>
  <link rel="stylesheet" href="/css/common.css" media="all"/>
<?php
$pageType = $this->model->getPageType();
if ($pageType == 2) {
// For the screen
	echo '  <link rel="stylesheet" href="/css/screen/layout.css" media="screen"/>
  <link rel="stylesheet" href="/css/screen/design.css" media="screen"/>
  <link rel="stylesheet" href="/css/printer/layout.css" media="print"/>
  <link rel="stylesheet" href="/css/printer/design.css" media="print"/>
  <script src="js/portrait_menu.js"></script>
 </head>
 <body onLoad="portraitMenuButton();" onResize="portraitMenuButton();">
  <header>
   <img src="/images/Shinto_torii_vermillion.svg.png" alt="Red hachiman torii"/>
   <h1>SL Shinto shrine register</h1>
  </header>
  <nav id="nav">
   <ul>
';
$pages = $this->model->getPageList(array(2));
$currentPageID = $this->model->getID();
foreach ($pages as $page) {
	if ($currentPageID == $page['id']) {
		echo '    <li id="active"><a href="../'.$page['route'].'"><em>'.$page['caption'].'</em></a>'."</li>\n";
	} else {
		echo '    <li><a href="../'.$page['route'].'">'.$page['caption'].'</a>'."</li>\n";
	}
}
echo '   </ul>
  </nav>
  <main>
   <section>
    '.$this->model->getPageContent().'
   </section>
   <a id="nav_link" href="#nav">Scroll to the navigation bar</a>
  </main>
  <footer id="footer">
   <p>Last change: 10. June 2017</p>
  </footer>';
} else {
// For the client
	echo '  <link rel="stylesheet" href="/css/client/layout.css" media="screen"/>
  <link rel="stylesheet" href="/css/client/design.css" media="screen"/>
 </head>
 <body>
  <section>
   '.$this->model->getPageContent();
	$articles = $this->model->getArticles();
	if (!empty($articles)) {
		foreach($articles as $article) {
			echo '   <article>';
			echo '    <header>';
			echo '     <h2 id="shrine_'.$article->getID().'">'.$article->getCaption().'</h2>';
			echo '    </header>';
			echo '    <img src="'.$article->getImage().'" width="100%">';
			echo '    <p>'.$article->getDescription().'</p>';
			echo '    <a href="'.$article->getLink().'">Teleport</a>';
			echo '   </article>';
		}
	}
	echo '  </section>';
}
?>
 </body>
</html>
