<meta http-equiv="Content-Type" content="text/html; charset=<?= $this->charset ?>"/>
<meta name="msapplication-TileColor" content="#ffffff"/>
<meta name="msapplication-TileImage" content="/mstile-144x144.png"/>
<meta name="author" content="Vivien Richter"/>
<meta name="description" content="<?= $this->model->getPageDescription(); ?>"/>
<meta name="keywords" content="<?= $this->model->getPageKeywords(); ?>"/>
<title><?= $this->model->getPageTitle(); ?></title>
<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico"/>
<link rel="icon" type="image/png" href="/favicon.png" sizes="32x32"/>
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/>
<!-- Matomo analytics -->
<script type="text/javascript">
  var _paq = window._paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//analytics.slsr.org/";
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', '1']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Matomo Code -->
