<meta http-equiv="Content-Type" content="text/html; charset=<?= $this->charset ?>"/>
<meta name="msapplication-TileColor" content="#ffffff"/>
<meta name="msapplication-TileImage" content="/mstile-144x144.png"/>
<meta name="author" content="Vivien Richter"/>
<meta name="description" content="<?= $this->model->getPageDescription(); ?>"/>
<meta name="keywords" content="<?= $this->model->getPageKeywords(); ?>"/>
<title><?= $this->model->getPageTitle(); ?></title>
<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico"/>
<link rel="icon" type="image/png" href="/favicon.png" sizes="32x32"/>
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/>
