<meta http-equiv="Content-Type" content="text/html; charset=<?= $this->charset ?>"/>
<meta name="msapplication-TileColor" content="#ffffff"/>
<meta name="msapplication-TileImage" content="/mstile-144x144.png"/>
<meta name="author" content="Vivien Richter"/>
<meta name="description" content="The Second Life Shinto Shrine Register (SLSR) is a association of Shinto shrines in Second Life."/>
<meta name="keywords" content="Second Life, SL, Shinto, shrine register, board"/>
<title><?= $this->model->getPageTitle(); ?></title>
<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico"/>
<link rel="icon" type="image/png" href="/favicon.png" sizes="32x32"/>
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/>
