<!DOCTYPE html>
<html lang="<?= $this->model->getLocale()->getLanguageCode($this->model->getLocale()->getCurrentLCID()) ?>">
    <head>
        <!-- Basic meta data -->
        <?php include BASE_DIRECTORY.'/templates/common/meta.phtml'; ?>
        <!-- Stylesheets -->
        <link rel="stylesheet" href="/css/board.css" media="screen"/>
        <!-- Matomo analytics -->
        <script type="text/javascript">
          var _paq = window._paq || [];
          /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
          _paq.push(['trackPageView']);
          _paq.push(['enableLinkTracking']);
          (function() {
            var u="//analytics.slsr.org/";
            _paq.push(['setTrackerUrl', u+'matomo.php']);
            _paq.push(['setSiteId', '1']);
            var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
            g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
          })();
        </script>
        <!-- End Matomo Code -->
    </head>
    <body>
        <main>
            <!-- Content -->
            <?php include BASE_DIRECTORY.'/templates/board/content.phtml'; ?>
        </main>
    </body>
</html>
