<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Basic meta data -->
        <?php include BASE_DIRECTORY.'/templates/common/meta.phtml'; ?>
        <!-- Stylesheets -->
        <link rel="stylesheet" href="/css/board.css" media="screen"/>
    </head>
    <body>
        <main>
            <!-- Content -->
            <?php include BASE_DIRECTORY.'/templates/board/content.phtml'; ?>
        </main>
    </body>
</html>
