   <section>
   	<header>
   		<h2><?= (($this->model->getPageType() == Page::PAGE_TYPE_CATEGORY || $this->model->getPageType() == Page::PAGE_TYPE_SUBPAGE) ? $this->model->getPageTitle() : $this->model->getPageCaption()) ?></h2>
   	</header>
    <?php
    echo $this->model->getPageContent();
	$articles = $this->model->getArticles();
	if (!empty($articles)) {
		foreach($articles as $article) {
			// Article template
			include 'article.phtml';
		}
	}
	?>
   </section>