  <nav id="nav" title="Navigation menu">
   <ul class="menu">
	<?php
	$pages = $this->model->getPageList(array(
		Page::PAGE_TYPE_NORMAL,
		Page::PAGE_TYPE_CATEGORY,
		Page::PAGE_TYPE_DEFAULT
	));
	$currentPage = $this->model;
	foreach ($pages as $page) {
		echo '<li'.(($currentPage->getID() == $page['id']) ? ' class="active"' : '').'>';
		echo '<a href="'.$this->model->getLocale()->localizeUrl('/'.$page['name']).'">'.$page['caption'].'</a>';
		if (($page['type'] == Page::PAGE_TYPE_CATEGORY) && ($currentPage->getPageType() == Page::PAGE_TYPE_CATEGORY || $currentPage->getPageType() == Page::PAGE_TYPE_SUBPAGE)) {
			echo '<ul>';
			$subPages = $this->model->getPageList(array(0));
			foreach ($subPages as $subPage) {
				echo '<li'.(($currentPage->getID() == $subPage['id']) ? ' class="active"' : '').'><a href="'.$this->model->getLocale()->localizeUrl('/'.$page['name'].'/'.$subPage['name']).'">'.$subPage['caption'].'</a>'."</li>\n";
			}
			echo '</ul>';
		}
		echo "</li>\n";
	}
	?>
   </ul>
  </nav>
