<!DOCTYPE html>
<html lang="<?= $this->model->getLocale()->getLanguageCode($this->model->getLocale()->getCurrentLCID()) ?>">
	<head>
		<!-- Basic meta data -->
		<?php include BASE_DIRECTORY.'/templates/common/meta.phtml'; ?>
		<!-- Localized pagelinks -->
		<?php include 'localized_pagelinks.phtml'; ?>
		<!-- Stylesheets -->
		<link rel="stylesheet" href="/css/screen.css" media="screen"/>
		<link rel="stylesheet" href="/css/printer.css" media="print"/>
		<!-- Responsive menu helper -->
		<script src="/js/responsive.js"></script>
		<!-- Season animations -->
		<?php
			$season = (new Season())->getName();
			if (($season == 'winter') || ($season == 'autumn')) echo '<script src="/js/animations/seasons/'.$season.'.js"></script>';
		?>
	</head>
	<body>
		<header>
			<!-- Banner -->
			<?php include 'header.phtml'; ?>
		</header>
		<nav>
			<!-- Navigation menu -->
			<?php include 'navigation.phtml'; ?>
			<!-- Language switch -->
			<?php include 'language_switch.phtml'; ?>
		</nav>
		<main>
			<!-- Content -->
			<?php include BASE_DIRECTORY.'/templates/browser/content.phtml'; ?>
			<a id="nav_link" href="#nav">Scroll to the navigation bar</a>
		</main>
		<footer>
			<!-- Copyright -->
			<?php include 'footer.phtml' ?>
		</footer>
	</body>
</html>
